#
# Squid config to define access rules for container clients. This is a stub
# config that containers should overwrite to allow external access.
#

# Whitelist domains.
#acl allowed_domains dstdomain www.example.com

# Whitelist local IPs.
#acl lan_server_1 dst 192.168.0.123/32
#acl lan_server_1_ports port 8080

# Allow rules.
#http_access allow client_net allowed_domains
#http_access allow client_net lan_server_1 lan_server_1_ports
