#
# Squid config to define additional safe ports for container clients. This is a
# stub config that containers can overwrite to allow access to more ports (e.g.,
# for FTP).
#

#acl Safe_ports port 21          # ftp
#acl Safe_ports port 22          # sftp
#acl Safe_ports port 990         # ftps
