#
# Squid proxy configuration for agent containers. This configuration is
# intentionally restrictive. This can be modified by replacing the following
# files:
#
# - "/etc/squid/ports.conf": Extra ports can be defined here. Default is no
#   extra ports.
# - "/etc/squid/access.conf": Access rules must be defined here. Default is no
#   external access.
#

#
# ACLs
#

# Source: container clients.
acl client_net src 10.89.0.0/16

# Ports.
acl Safe_ports port 80          # http
acl Safe_ports port 443         # https
acl Safe_ports port 1025-65535  # unregistered ports
include /etc/squid/ports.conf

#
# Access rules.
#

# Deny requests to certain unsafe ports.
http_access deny !Safe_ports

# Only allow cachemgr access from localhost.
http_access allow localhost manager
http_access deny manager

# Protect cloud servers that provide local users with sensitive info about
# their server via certain well-known link-local (a.k.a. APIPA) addresses.
http_access deny to_linklocal

# Include agent client access rules.
include /etc/squid/access.conf

# Deny access to localhost not previously allowed above.
http_access deny to_localhost

# Deny all other access.
http_access deny all

#
# Network.
#
http_port 3128
pid_filename /run/squid/squid.pid
shutdown_lifetime 0 seconds

#
# Logging.
#
access_log /var/log/squid/access.log squid all
cache_log /dev/null
cache_store_log none
debug_options ALL,1 11,3
logfile_rotate 0

#
# Disable caching.
#
cache deny all

coredump_dir /run/squid
